// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: connect.proto

package connectclient

import (
	"context"

	"go-im/connect/connect"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = connect.Request
	Response = connect.Response

	Connect interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultConnect struct {
		cli zrpc.Client
	}
)

func NewConnect(cli zrpc.Client) Connect {
	return &defaultConnect{
		cli: cli,
	}
}

func (m *defaultConnect) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := connect.NewConnectClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
