// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: connect.proto

package server

import (
	"context"

	"go-im/connect/connect"
	"go-im/connect/internal/logic"
	"go-im/connect/internal/svc"
)

type ConnectServer struct {
	svcCtx *svc.ServiceContext
	connect.UnimplementedConnectServer
}

func NewConnectServer(svcCtx *svc.ServiceContext) *ConnectServer {
	return &ConnectServer{
		svcCtx: svcCtx,
	}
}

func (s *ConnectServer) Ping(ctx context.Context, in *connect.Request) (*connect.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
